### ISSUE TITLE
spike not showing activity on map

### ISSUE THREAD

**Issue by mikelmaron** [jenningsanderson/data-team-edits#5]
here’s another weird issue, nothing showing for Kaart on that spike

![screen shot 2018-09-10 at 9 51 10 am](https://user-images.githubusercontent.com/22896/45302289-e441ed80-b4e0-11e8-9048-9bf109319691.png)

**Comment by jenningsanderson** [comment]
![image](https://user-images.githubusercontent.com/1637425/45305460-92489a00-b4d7-11e8-9f2d-a0048b2ed98c.png)

@mikelmaron - So, for curiosity -- apparently that was the day^ (2016-11-22); the bulk of the edits are in Santiago, Chile. Unfortunately it's not showing up until Zoom level 5 because of the way that it's clustering the points at low zoom levels (and then filtering on top of that)... will see how I can preserve this and keep tiles a reasonable size.

**Comment by jenningsanderson** [comment]
Fixed this with a new lower-zoom aggregation step based on parent-tiles.
